# Generated by Django 3.2.9 on 2024-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20240420_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('complaint', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterForm2',
        ),
    ]
