# Generated by Django 3.2.9 on 2024-04-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sector',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
