# Generated by Django 5.0.4 on 2024-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_kitap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('user_review', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('pdf', models.FileField(upload_to='book_pdfs/')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Kitap',
        ),
    ]
