# Generated by Django 5.0.4 on 2024-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_updated_at_remove_post_views_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sector',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
