# Generated by Django 5.0.4 on 2024-05-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comment_image_comment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, choices=[('Galatasaray Üniversitesi', 'Galatasaray Üniversitesi'), ('İstanbul Teknik Üniversitesi', 'İstanbul Teknik Üniversitesi'), ('Orta Doğu Teknik Üniversitesi', 'Orta Doğu Teknik Üniversitesi')], max_length=100),
        ),
    ]
