# Generated by Django 5.0.4 on 2024-05-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_profile_age_profile_bio_profile_email_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
